Your code will be given a 1D NumPy array. Your code should reverse the order of the array and return it. For example, if the input is [1,2,3,4,5], your code should output [5,4,3,2,1].

In [45]:
import numpy as np

arr = [1,2,3,4,5]

def reverse(arr):
    revarr = [ ]
    i=0
    while i < len(arr):
        revarr = np.append(revarr, arr[(len(arr)-1-i)])
        i += 1
    return revarr

In [46]:
reverse(arr)

array([5., 4., 3., 2., 1.])

In [35]:
reverse(reverse(arr))

array([1., 2., 3., 4., 5.])

In [67]:
def reverse(arr):
    revarr = []
    i= -1
    while i >= (-len(arr)):
        revarr = np.append(revarr, arr[i])
        i -= 1
    return revarr

In [68]:
reverse(arr)

array([5., 4., 3., 2., 1.])