<img src="https://www.mines.edu/webcentral/wp-content/uploads/sites/267/2019/02/horizontallightbackground.jpg" width="100%"> 
### CSCI250 Python Computing: Building a Sensor System
<hr style="height:5px" width="100%" align="left">

# `numpy`: 1D arrays

# Objectives
* introduce 1D `numpy` arrays and operations
* discuss `numpy` array 
    * attributes
    * slicing & striding

# Resources
* [numpy.org](http://www.numpy.org)
* [`numpy` user guide](https://docs.scipy.org/doc/numpy/user)
* [`numpy` reference](https://docs.scipy.org/doc/numpy/reference)

# `import`
`numpy` comes with methods optimized for array operations. 

Can be accessed by typing a variable name, followed by `.` and **TAB**. 

The name of the method followed by `?` returns the selfdoc. 

In [1]:
import numpy as np

# array creation
There are multiple mechanisms to define 1D `numpy` arrays.

## `np.array()`
Create a `numpy` array from a Python list.

In [3]:
a = np.array( [4 ,3 ,5 ,7 ,6 ,8], dtype=float)
print(a)
type(a)

[4. 3. 5. 7. 6. 8.]


numpy.ndarray

## `np.empty()`
Form an array of given shape and type, without initializing entries.

Fast, but use with caution!

In [4]:
n = 6

eI = np.empty(n, dtype=int)
eF = np.empty(n, dtype=float)
eB = np.empty(n, dtype=bool)
eC = np.empty(n, dtype=complex)

In [5]:
print(eI)
print(eF)
print(eB)
print(eC)

[39119600        0        0        0        0        0]
[4. 3. 5. 7. 6. 8.]
[ True  True  True  True  True  True]
[-2.37781275e-044+1.06099790e-312j  1.01855798e-312+9.54898106e-313j
  1.20953760e-312+1.06099790e-312j  1.23075756e-312+1.06099790e-312j
  1.08221785e-312+9.76118064e-313j  1.14587773e-312+1.90979621e-312j]


## `np.zeros()`
Returns a new array of given shape and type, filled with zeros.

In [6]:
zI = np.zeros(n, dtype=int)
zF = np.zeros(n, dtype=float)
zB = np.zeros(n, dtype=bool)
zC = np.zeros(n, dtype=complex)

In [7]:
print(zI)
print(zF)
print(zB)
print(zC)

[0 0 0 0 0 0]
[0. 0. 0. 0. 0. 0.]
[False False False False False False]
[0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j 0.+0.j]


## `np.ones()`
Returns a new array of given shape and type, filled with ones.

In [8]:
oI = np.ones(n, dtype=int)
oF = np.ones(n, dtype=float)
oB = np.ones(n, dtype=bool)
oC = np.ones(n, dtype=complex)

In [9]:
print(oI)
print(oF)
print(oB)
print(oC)

[1 1 1 1 1 1]
[1. 1. 1. 1. 1. 1.]
[ True  True  True  True  True  True]
[1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j 1.+0.j]


## `np.arange()`

Return evenly spaced values from `start` to `stop`, given `step`. 

Can be used for different data types.

In [10]:
start = 0
stop = 10
step = 1

In [11]:
a = np.arange(start, stop, step, dtype=float)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


## `np.linspace()`
Returns `num` evenly spaced numbers from `start` to `stop`. 

Can be used for different data types.

In [12]:
start = 0
stop = 10
num = 10

In [13]:
a = np.linspace(start, stop, num, dtype=float)
print(a)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


## `np.logspace()`
Return numbers spaced evenly on a log scale. 

Can be used for different data types.

In [14]:
start = -2
stop = +2
num = 5

In [15]:
a = np.logspace(start, stop, num, dtype=float)
print(a)

[1.e-02 1.e-01 1.e+00 1.e+01 1.e+02]


# array indexing

Access an element of a `numpy` array using its index (starts with `0`).

`ndarray` type is **mutable**.

In [20]:
a = np.array( [4, 3, 5, 7, 6, 8], dtype=int)
print(a)
print( id(a) )

[4 3 5 7 6 8]
2910005352


We can use positive indexes - count from the start of the array.

In [21]:
print(a)
a[ +3 ] = -9
print(a)
print( id(a) )

[4 3 5 7 6 8]
[ 4  3  5 -9  6  8]
2910005352


We can use negative indexes - count from the end of the array.

In [22]:
print(a)
a[ -3 ] = +9
print(a)
print( id(a) )

[ 4  3  5 -9  6  8]
[4 3 5 9 6 8]
2910005352


# array slicing
We can access/modify a range of elements in a 1D `numpy` array. 

In [23]:
a = np.array( [4, 3, 5, 7, 6, 8], dtype=int)
print(a)

[4 3 5 7 6 8]


In [24]:
a[ 2:4 ] = 0
print(a)

[4 3 0 0 6 8]


# array attributes
Reflect information that is intrinsic to the array. 

<img src="http://www.dropbox.com/s/fcucolyuzdjl80k/todo.jpg?raw=1" width="10%" align="right">

Explain the **attributes** associated with 1D `ndarray`s.
* Add comments explaining their purpose. 
* Include examples demonstrating their usage.

In [25]:
o = np.ones( n )

In [26]:
o.ndim

1

In [27]:
o.shape

(6,)

In [28]:
o.size

6

In [29]:
o.dtype

dtype('float64')

In [30]:
o.nbytes

48

In [31]:
o.itemsize

8

# array methods
Array methods facilitate efficient operations on `numpy` arrays.

<img src="http://www.dropbox.com/s/fcucolyuzdjl80k/todo.jpg?raw=1" width="10%" align="right">

Explain the **methods** associated with 1D `ndarray`s.
* Add comments explaining their purpose. 
* Include examples demonstrating their usage.

## `ndarray.fill()`
Fills an array with a scalar value.

In [32]:
a = np.array( [4, 3, 5, 7, 6, 8], dtype=int )
print(a)

[4 3 5 7 6 8]


In [33]:
a.fill(-1)
print(a)

[-1 -1 -1 -1 -1 -1]


## `ndarray.item()`
Return an `ndarray` element as a standard Python scalar.

In [34]:
a = np.array( [4, 3, 5, 7, 6, 8], dtype=int )
print(a)

print(a.item(5))

[4 3 5 7 6 8]
8


## `ndarray.nonzero()`
Return the indexes of nonzero `ndarray` elements.

In [38]:
a = np.array( [4, 3, 5, 7, 6, 8], dtype=int ) % 2
print(a)

[0 1 1 1 0 0]


In [39]:
b = a.nonzero()
print(b[0])

[1 2 3]


## `ndarray.put()`
Replaces specified elements of an array with given values.

In [40]:
a = np.array( [4, 3, 5, 7, 6, 8], dtype=int )
print(a)

[4 3 5 7 6 8]


In [41]:
indexes = [ 0, 1, 4]
values  = [-1,-2,-3]

a.put(indexes,values)
print(a)

[-1 -2  5  7 -3  8]


## `ndarray.clip()`
Clips (limit) the values in an array.

In [ ]:
a = np.array( [4, 3, 5, 7, 6, 8], dtype=int ) - 5
print(a)

In [ ]:
print(a.clip(-1,1))

## `ndarray.round()`
Evenly rounds to the given number of decimals.

In [42]:
a = np.array( [4, 3, 5, 7, 6, 8], dtype=int ) / 2
print(a)

[2.  1.5 2.5 3.5 3.  4. ]


In [43]:
b = a.round(0)
print(b)

[2. 2. 2. 4. 3. 4.]


## `ndarray.sort()`
Sort an `ndarray` in place.

In [44]:
a = np.array( [4, 3, 5, 7, 6, 8], dtype=int )
print(a)

[4 3 5 7 6 8]


In [45]:
a.sort()
print(a)

[3 4 5 6 7 8]


## `ndarray.take()`
Take elements from an array along an axis.

In [46]:
a = np.array( [4, 3, 5, 7, 6, 8], dtype=int )
print(a)

[4 3 5 7 6 8]


In [47]:
indices = [0,1,4]
a.take(indices)

array([4, 3, 6])

## `ndarray.min()`, `ndarray.max()`
Return the min/max of the array along an axis.

In [48]:
a = np.array( [4, 3, 5, 7, 6, 8], dtype=int )
print(a)

[4 3 5 7 6 8]


In [49]:
print( a.min(0) )
print( a.max(0) )

3
8


## `ndarray.mean()`
Compute the arithmetic mean of the array along an axis.

In [50]:
a = np.array( [4, 3, 5, 7, 6, 8], dtype=int )
print(a)

[4 3 5 7 6 8]


In [51]:
print( a.mean(0) )

5.5


## `ndarray.std()`, `ndarray.var()`
Compute the standard deviation or variance along an axis.

In [52]:
a = np.array( [4, 3, 5, 7, 6, 8], dtype=int )
print(a)

[4 3 5 7 6 8]


In [53]:
print( a.var(0) )
print( a.std(0) )

2.9166666666666665
1.707825127659933


## `ndarray.argmin()`,  `ndarray.argmax()`
Returns the indexes of the min/max values along an axis.

In [54]:
a = np.array( [4, 3, 5, 7, 6, 8], dtype=int )
print(a)

[4 3 5 7 6 8]


In [55]:
print(a.argmin())
print(a.argmax())

1
5


## `ndarray.argsort()`
Returns the indices that would sort an array.

In [56]:
a = np.array( [4, 3, 5, 7, 6, 8], dtype=int )
print(a)

[4 3 5 7 6 8]


In [57]:
b = a.argsort()
print(b)

[1 0 2 4 3 5]


## `ndarray.sum()`, `ndarray.prod()`
Return the sum /product of the array along an axis.

In [58]:
a = np.array( [4, 3, 5, 7, 6, 8], dtype=int )
print(a)

[4 3 5 7 6 8]


In [59]:
print(a.sum())
print(a.prod())

33
20160


## `ndarray.cumsum()`, `ndarray.cumprod()`
Return the cumulative sum/product of the array along an axis.

In [60]:
a = np.array( [4, 3, 5, 7, 6, 8], dtype=int )
print(a)

[4 3 5 7 6 8]


In [61]:
print(a.cumsum())
print(a.cumprod())

[ 4  7 12 19 25 33]
[    4    12    60   420  2520 20160]


## `ndarray.real`, `ndarray.imag`
Return the real/imaginary part of a complex array.

In [62]:
a = np.array( [4-1j, 3+2j, 5+1j, 7, 6-2j, 8+4j], dtype=complex)
print(a)

[4.-1.j 3.+2.j 5.+1.j 7.+0.j 6.-2.j 8.+4.j]


In [63]:
print(a.real)
print(a.imag)

[4. 3. 5. 7. 6. 8.]
[-1.  2.  1.  0. -2.  4.]


<img src="https://www.dropbox.com/s/7vd3ezqkyhdxmap/demo.png?raw=1" width="10%" align="left">

# Demo

A sequence for computing number $\pi$ credited to **Gottfried Leibniz** is:

$$\dfrac{\pi}{4} = \sum\limits_{i=1}^{n} \dfrac{ (-1)^{i+1} }{2i-1}$$

* Use `numpy` to compute number $\pi$ for a set number of terms.
* Compare the value with the one from the `math` module.

Define a `numpy` array for integers $1\le i \le n$:

In [64]:
n = 1000

In [78]:
i = np.arange(1,n+1, dtype=int)

Compute the terms of the series using `numpy` methods:

In [79]:
myTerms = 4.0*( np.power(-1,i+1) / (2*i-1) )

Compute $\pi$ using `numpy` methods:

In [80]:
myPi = myTerms.sum()

Compare the user-defined $\pi$ with the one provided by `math`:

In [81]:
import math

print('     my pi:',myPi)
print('   math pi:',math.pi)
print('difference:',myPi - math.pi)

     my pi: 3.140592653839792
   math pi: 3.141592653589793
difference: -0.0009999997500012014


<img src="https://www.dropbox.com/s/wj23ce93pa9j8pe/demo.png?raw=1" width="10%" align="left">

# Exercise

A sequence for computing number $\pi$ is:

$$\dfrac{\pi}{\sqrt{12}} = \sum\limits_{i=0}^{n} \dfrac{(-1)^{i}}{3^i(2i+1)}$$

* Use `numpy` to compute number $\pi$ for a set number of terms.
* Compare the value with the one from the `math` module.

In [82]:
n = 1000
i = np.arange(0,n, dtype=int)

piSeq = (np.sqrt(12)*np.power(-1, i))/(np.power(3, i)*(2*i+1))
pi2 = piSeq.sum()

print('     my pi:',myPi)
print('      pi 2:', pi2)
print('   math pi:',math.pi)
print('myPi difference:',myPi - math.pi)
print(' pi2 difference:', pi2 - math.pi)

     my pi: 3.140592653839792
      pi 2: 3.1415573775650585
   math pi: 3.141592653589793
myPi difference: -0.0009999997500012014
 pi2 difference: -3.527602473463176e-05
