<img src="https://www.mines.edu/webcentral/wp-content/uploads/sites/267/2019/02/horizontallightbackground.jpg" width="100%"> 
### CSCI250 Python Computing: Building a Sensor System
<hr style="height:5px" width="100%" align="left">

# `numpy`: 1D vectorization

# Objectives
* introduce fast vectorized `numpy` array operations
* evaluate computational speed-up relative to loops
* discuss aggregations and masking applied to `numpy` arrays 

# Resources
* [numpy.org](http://www.numpy.org)
* [`numpy` user guide](https://docs.scipy.org/doc/numpy/user)
* [`numpy` reference](https://docs.scipy.org/doc/numpy/reference)
* [`numpy` ufuncs](https://numpy.org/doc/stable/reference/ufuncs.html)

# Definition

**Vectorization**: a computational style in which multiple operations are executed at once, i.e. execute a single global operation instead of multiple smaller operations in a loop. 

Has multiple advantages:
* **compact appearance**: the code resembles math
* **error reduction**: the code is shorter, less complex
* **execution performance**: the code runs much faster

# Vectorized calculations

Computational speed-up can be achieved using two main methods:
1. universal functions 
2. fast array selection 

# 1. universal functions (ufuncs)

* operate element-by-element on `numpy` arrays
* are often implemented in compiled C code

Some are called automatically when the infix notation is clear:
* `np.add(a,b)` is called for `a + b`

In [1]:
import numpy as np
import math,time

## arithmetic ufuncs

* `np.add(),np.multiply(),np.floor_divide(),...`

or

* `+, *, //, ...`

In [2]:
n = int(1e6)

a = np.linspace(0,1,n, dtype=float)
b = np.linspace(1,0,n, dtype=float)
c = np.empty(       n, dtype=float)

**non-vectorized code** (uses loops)

In [8]:
tick = time.time()

for i in range(n):
    c[i] = a[i] * b[i]
    
tock = time.time()
dLOOP = int((tock-tick)*1e6)

print( int(c.sum()), dLOOP,'us' )

166666 1762627 us


**vectorized code** (does not use loops)

In [9]:
tick = time.time()

c = a * b

tock = time.time()
dVECT = int((tock-tick)*1e6)
print( int(c.sum()), dVECT, 'us')

166666 38110 us


The **execution time** ratio is

In [10]:
int(dLOOP/dVECT)

46

## comparison ufuncs
* `np.less(),np.greater(),np.not_equal(),...`

or

* `<, >, !=, ...`

In [11]:
n = 11
a = np.linspace(0,1,n, dtype=float)
b = np.linspace(1,0,n, dtype=float)
print(a)
print(b)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
[1.  0.9 0.8 0.7 0.6 0.5 0.4 0.3 0.2 0.1 0. ]


In [12]:
print( np.greater(a,b) )  # ufunc

[False False False False False False  True  True  True  True  True]


In [13]:
print( a > b )            # infix

[False False False False False False  True  True  True  True  True]


## bitwise ufuncs
* `np.bitwise_and(),np.left_shift(),...`

or

* `&, >>, ...`

In [14]:
n = 11
a = np.linspace(0,n,n, dtype=int)
b = np.linspace(n,0,n, dtype=int)
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 11]
[11  9  8  7  6  5  4  3  2  1  0]


In [15]:
print( np.bitwise_and(a,b) ) # ufunc

[0 1 0 3 4 5 4 3 0 1 0]


In [16]:
print( a & b )               # infix

[0 1 0 3 4 5 4 3 0 1 0]


## logical ufuncs

`np.logical_and(),np.logical_or(),...`

**N.B.**: no infix equivalents

In [17]:
n = 11
a = np.linspace(0,1,n, dtype=float) > 0.25
b = np.linspace(0,1,n, dtype=float) > 0.75
print(a)
print(b)

[False False False  True  True  True  True  True  True  True  True]
[False False False False False False False False  True  True  True]


In [18]:
print( np.logical_and(a,b)) # ufunc

[False False False False False False False False  True  True  True]


In [19]:
print( a and b )            # 

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

## trigonometric ufuncs
`np.sin(),np.arcsin(),np.sinh(),...`

## exp/log ufuncs
`np.exp(),np.log(),np.log10(),...`

`...`

## aggregation ufuncs

`np.sum()`, `np.prod()`

In [20]:
n = int(1e6)
a = np.linspace(0,1,n, dtype=float) > 0.25

In [21]:
tick = time.time()

s = sum(a)

tock = time.time()
print( int(s), int((tock-tick)*1e6),'us' )

750000 9557907 us


In [22]:
tick = time.time()

s = np.sum(a)

tock = time.time()
print( int(s), int((tock-tick)*1e6), 'us' )

750000 6836 us


## more aggregation ufuncs

`np.min()`, `np.max()`

`np.all()`,`np.any()`

`np.mean()`, `np.median()`, `np.var()`, `np.std()`

`np.argmin()`, `np.argmax()`, `np.nanmin()`, `np.nanmax()`

`...`

In [1]:
#np.mean
help('numpy.mean')

Help on function mean in numpy:

numpy.mean = mean(a, axis=None, dtype=None, out=None, keepdims=<no value>)
    Compute the arithmetic mean along the specified axis.
    
    Returns the average of the array elements.  The average is taken over
    the flattened array by default, otherwise over the specified axis.
    `float64` intermediate and return values are used for integer inputs.
    
    Parameters
    ----------
    a : array_like
        Array containing numbers whose mean is desired. If `a` is not an
        array, a conversion is attempted.
    axis : None or int or tuple of ints, optional
        Axis or axes along which the means are computed. The default is to
        compute the mean of the flattened array.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, a mean is performed over multiple axes,
        instead of a single axis or all the axes as before.
    dtype : data-type, optional
        Type to use in computing the mean.  For integer i

<img src="http://www.dropbox.com/s/fcucolyuzdjl80k/todo.jpg?raw=1" width="10%" align="right">

Add examples to experiment with [`numpy` ufuncs](https://numpy.org/doc/stable/reference/ufuncs.html#available-ufuncs). 

Compare execution time with and without vectorized codes.

**N.B.**: use large arrays for relevant speed-up comparison.

# 2. Fast array selection

Methods to efficiently slice `numpy` arrays:
* fancy indexing
* array masking

## fancy indexing
Array indexing using arrays of integers.

In [23]:
nin = int(1e6)       # n before decimation
jmp = 100            #   decimation factor
nou = int(nin/jmp)   # n  after decimation

In [24]:
a = np.linspace(0,1,nin, dtype=float)
print(a.size)

1000000


In [25]:
c = np.empty(nou, dtype=float)
print(c.size)

10000


**non-vectorized code** (uses loops)

In [34]:
tick = time.time()

for i in range(nou):
    c[i] = a[ i*jmp ]
    
tock = time.time()
dLOOP = int((tock-tick)*1e6)

print( int(c.sum()), dLOOP,'us' )

4999 33918 us


**vectorized code** (does not use loops)

In [35]:
# form array of indexes by list comprehension
k = np.array( [i for i in range(0,nin,jmp)] )
print(k.size)

10000


In [44]:
tick = time.time()

c = a[k]
    
tock = time.time()
dVECT = int((tock-tick)*1e6)

print( int(c.sum()), dVECT,'us' )

4999 1731 us


In [45]:
int(dLOOP/dVECT)

19

## array masking
Array selection using vectorized logical operations.

In [46]:
n = int(1e6)

a = np.linspace(0,1,n, dtype=float)

aLo = 0.50
aHi = 0.75

**non-vectorized code** (uses loops)

In [47]:
c = np.zeros(n, dtype=float) 

In [52]:
tick = time.time()

j = 0
for i in range(n):
    if (a[i]<aLo) | (a[i]>aHi):
        c[j] = a[i]
        j += 1
    
tock = time.time()
dLOOP = int((tock-tick)*1e6)

print( int(c.sum()), dLOOP,'us' )

print(c.size) # output size = input size (inefficient)

343749 2951924 us
750000


**vectorized code** (does not use loops)

In [53]:
tick = time.time()

c = a[ (a<aLo) | (a>aHi) ]
    
tock = time.time()
dVECT = int((tock-tick)*1e6)

print( int(c.sum()), dVECT,'us' )

print(c.size) # automatically size output

343749 85797 us
750000


In [51]:
int(dLOOP/dVECT)

36

<img src="http://www.dropbox.com/s/fcucolyuzdjl80k/todo.jpg?raw=1" width="10%" align="right">

Add examples to experiment with 
* fancy indexing 
* fast array masking.

Compare execution time with and without vectorized codes.

**N.B.**: use large arrays for relevant speed-up comparison.

<img src="https://www.dropbox.com/s/wj23ce93pa9j8pe/demo.png?raw=1" width="10%" align="left">

# Exercise

A sequence for computing number $\pi$ is:

$$\dfrac{\pi}{\sqrt{12}} = \sum\limits_{i=0}^{n} \dfrac{(-1)^{i}}{3^i(2i+1)}$$

* Use `numpy` vectorization to compute $\pi$ for $n$ terms.
* Evaluate the speed-up of the vectorized implementation.

**N.B.**: do not use loops.